eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
server:
  port: 8084  
spring:
  jpa:
    show-sql: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/blog
    username: blog-user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true